apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  labels:
    app: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do echo "notifier alive $(date) token=${API_TOKEN}"; sleep 30; done
          envFrom:
            - secretRef:
                name: lab4-secret
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
